// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJgWEkOEz4_kYpNoILflYsn8FSln-OwT0',
    appId: '1:34130246658:web:8bab8024cfe9e2342cfb1b',
    messagingSenderId: '34130246658',
    projectId: 'ecommerce-ict',
    authDomain: 'ecommerce-ict.firebaseapp.com',
    storageBucket: 'ecommerce-ict.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOd1NlltLjF1zLJc_RuaFyBoqeMMd9Xus',
    appId: '1:34130246658:android:a9a6ae234e983fd92cfb1b',
    messagingSenderId: '34130246658',
    projectId: 'ecommerce-ict',
    storageBucket: 'ecommerce-ict.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAekZaAjD-PzWyfkofuwemWlJmaLJ9rrn8',
    appId: '1:34130246658:ios:5fd347f7c6ee48302cfb1b',
    messagingSenderId: '34130246658',
    projectId: 'ecommerce-ict',
    storageBucket: 'ecommerce-ict.appspot.com',
    iosBundleId: 'com.example.ecommerceTask3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAekZaAjD-PzWyfkofuwemWlJmaLJ9rrn8',
    appId: '1:34130246658:ios:027e2f92a60da8b62cfb1b',
    messagingSenderId: '34130246658',
    projectId: 'ecommerce-ict',
    storageBucket: 'ecommerce-ict.appspot.com',
    iosBundleId: 'com.example.ecommerceTask3.RunnerTests',
  );
 }
